/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://ifnkeqp5gjhzrac6ulrfeuuhsu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-x2xcgfpefjhdphcrm2mdddbmye",
    "aws_cognito_identity_pool_id": "us-west-2:e1093d98-5285-4a0c-9245-a5a520faac6a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_ZKE7LUMnz",
    "aws_user_pools_web_client_id": "1fmticja332r57r5jfrklot4q2",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "avannis-data-processing223730-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
